apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: openstack-ca-cert
spec:
  strategy: "Reconcile"
  clusterSelector:
      matchLabels:
        cloud-provider: openstack
  resources:
    - name: openstack-ca-cert
      kind: Secret