apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cert-manager
spec:
  clusterSelector:
    matchLabels:
      cloud-provider: openstack
      app: digitalhub
      env: bologna
  repoURL: https://charts.jetstack.io
  chartName: cert-manager
  namespace: cert-manager
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
  valuesTemplate: |
    installCRDs: true