apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: ingress-nginx
spec:
  clusterSelector:
    matchLabels:
      cloud-provider: openstack
      ingress-controller: ingress-nginx
      app: digitalhub
      env: bologna
  repoURL: https://kubernetes.github.io/ingress-nginx
  chartName: ingress-nginx
  namespace: ingress-nginx
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
  valuesTemplate: |
    controller:
      allowSnippetAnnotations: true