apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: relector
spec:
  clusterSelector:
    matchLabels:
      app: digitalhub
      env: bologna
  repoURL: https://emberstack.github.io/helm-charts
  chartName: reflector
  namespace: reflector
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true