apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
 name: wildcard-certificate-dns
spec:
 strategy: "Reconcile"
 clusterSelector:
   matchLabels:
      cloud-provider: openstack
      app: digitalhub
      env: bologna
 resources:
   - name: wildcard-certificate-dns
     kind: ConfigMap