apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: digitalhub-bologna
  name: patch-secret
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update"]